mysit/blogging/urls.py
from django.urls import path
from blogging.views import PostListView, PostDetailView
from django.urls import path, include
from rest_framework import routers

urlpatterns = [
    path('', PostListView.as_view(), name="blog_index"),
    path('posts/<int:pk>/', PostDetailView.as_view(), name="blog_detail"),
]

mysit/mysit/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from blogging import views
from django.contrib.auth.views import LoginView, LogoutView

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'posts', views.PostViewSet)
router.register(r'categories', views.CategoryViewSet)

urlpatterns = [
    path('polling/', include('polling.urls')),
    path('admin/', admin.site.urls),
    path('', include('blogging.urls')),
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', LogoutView.as_view(next_page='/'), name="logout"),
    path('', include(router.urls)),
    path("api/", include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

mysit/polling/urls.py
from django.urls import path
from polling.views import PollListView, PollDetailView

urlpatterns = [
    path("", PollListView.as_view(), name="poll_index"),
    path("polls/<int:pk>/", PollDetailView.as_view(), name="poll_detail"),
]

mysit/blogging/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    def __str__(self):
        return self.title
        
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

class Category(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name='categories')

    class Meta:
        verbose_name_plural = 'Categories'

mysit/mysit/quickstart/models.py
from django.db import models

# Create your models here.

mysit/polling/models.py
from django.db import models

# Create your models here.

class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

mysit/blogging/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from django.contrib.auth.models import User
from blogging.models import Post, Category
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from rest_framework import viewsets
from rest_framework import permissions
from blogging.serializers import UserSerializer, CategorySerializer, PostSerializer

class PostListView(ListView):
    template_name = 'blogging/list.html'
    queryset = Post.objects.exclude(published_date__exact=None).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post
    template_name = 'blogging/detail.html'
    queryset = Post.objects.filter(published_date__isnull=False)

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

class PostViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows posts to be viewed or edited.
    """
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

class CategoryViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows categories to be viewed or edited.
    """
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

mysit/mysit/quickstart/views.py
from django.shortcuts import render

from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions
from mysit.quickstart.serializers import UserSerializer, GroupSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

mysit/polling/views.py
from django.shortcuts import render
from django.http import Http404
from polling.models import Poll
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


class PollListView(ListView):
    model = Poll
    template_name = 'polling/list.html'


class PollDetailView(DetailView):
    model = Poll
    template_name = 'polling/detail.html'

    def post(self, request, *args, **kwargs):
        poll = self.get_object()

        if request.POST.get("vote") == "Yes":
            poll.score += 1
        else:
            poll.score -= 1
        poll.save()

        context = {"object": poll}
        return render(request, "polling/detail.html", context)

mysit/blogging/templates/blogging/detail.html
{% extends "base.html" %}

{% block content %}
<a class="backlink" href="/">Home</a>
<h1>{{ object }}</h1>
<p class="byline">
  Posted by {{ object.author.username }} &mdash; {{ object.published_date }}
</p>
<div class="post-body">
  {{ object.text }}
</div>
<ul class="categories">
  {% for category in object.categories.all %}
    <li>{{ category }}</li>
  {% endfor %}
</ul>
{% endblock %}

mysit/blogging/templates/blogging/list.html
{% extends "base.html" %}{% block content %}
  <h1>Recent Posts</h1>
  {% comment %} here is where the query happens {% endcomment %}
  {% for post in post_list %}
  <div class="post">
    <h2>           
      <a href="{% url 'blog_detail' post.pk %}">{{ post }}</a>
    </h2>
    <p class="byline">
      Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
    </p>
    <div class="post-body">
      {{ post.text }}
    </div>
    <ul class="categories">
      {% for category in post.categories.all %}
        <li>{{ category }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endfor %}
{% endblock %}

mysit/mysit/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>My Django Blog</title>
    <link type="text/css" rel="stylesheet" href="{% static 'django_blog.css' %}">
  </head>
  <body>
    <div id="header">  {# header begins here #}
      <ul id="control-bar">
      {% if user.is_authenticated %}
       {% if user.is_staff %}<li><a href="{% url 'admin:index' %}">admin</a></li>{% endif %}
        <li><a href="{% url 'logout' %}">logout</a></li>
       {% else %}
        <li><a href="{% url 'login' %}">login</a></li>
      {% endif %}
      </ul>
    </div> 
    <div id="container">
      <div id="content">
      {% block content %}
       [content will go here]
      {% endblock %}
      </div>
    </div>
  </body>
</html>

mysit/mysit/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>My Blog Login</h1>
<form action="" method="POST">{% csrf_token %}
  {{ form.as_p }}
  <p><input type="submit" value="Log In"></p>
</form>
{% endblock %}

mysit/polling/templates/polling/detail.html
{# polling/templates/polling/detail.html #}

{% extends "base.html" %}
{% block content %}
<h1>{{ object.title }}</h1>
<div class="poll-body">
    {{ object.text }}
</div>
<div class="poll-score">
    Current score: {{ object.score }}
</div>
<div class="poll-vote">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="vote" value="Yes">
        <input type="submit" name="vote" value="No">
    </form>
</div>
{% endblock %}

mysit/polling/templates/polling/list.html
{# polling/templates/polling/list.html #}
{% extends "base.html" %}
{% block content %}
<h1>Polls</h1>
{% for poll in poll_list %}
    <div class="poll">
        <h2>
            <a href="{% url 'poll_detail' poll.pk %}">{{ poll.title }}</a>
        </h2>
    </div>
{% endfor %}
{% endblock %}